---
name: Publish Image
description: Build and push Docker images to multiple registries
author: "Wes Dean"
branding:
  icon: package
  color: blue

inputs:
  github_ref:
    description: "GitHub ref"
    required: true

  repository_name:
    description: "Repository name"
    required: true

  dockerfile:
    description: "Path to the Dockerfile to build (defaults to Dockerfile in the build context)"
    required: false

  context:
    description: "Path to the build context"
    required: false
    default: "."

  force_release:
    description: "Force release-related tags, even if not a release"
    required: false
    default: false

  platforms:
    description: "Platforms to build for"
    required: false
    default: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"

  dockerhub_image:
    description: "Dockerhub image name"
    required: false
  dockerhub_username:
    description: "DockerHub username"
    required: false
  dockerhub_token:
    description: "DockerHub access token"
    required: false
  dockerhub_registry:
    description: "DockerHub registry URL"
    required: false
    default: "docker.io"

  ghcr_image:
    description: "GitHub Container Registry image name"
    required: false
  ghcr_username:
    description: "GitHub Container Registry username"
    required: false
  ghcr_token:
    description: "GitHub Container Registry personal access token (PAT)"
    required: false
  ghcr_registry:
    description: "GitHub Container Registry URL"
    required: false
    default: "ghcr.io"

  quay_image:
    description: "Quay image name"
    required: false
  quay_username:
    description: "Quay username"
    required: false
  quay_token:
    description: "Quay access token"
    required: false
  quay_registry:
    description: "Quay registry URL"
    required: false
    default: "quay.io"

  harbor_image:
    description: "Harbor image name"
    required: false
  harbor_username:
    description: "Harbor username"
    required: false
  harbor_token:
    description: "Harbor access token"
    required: false
  harbor_registry:
    description: "Harbor registry URL"
    required: false
    default: "goharbor.io"

  ecr_image:
    description: "ECR image name"
    required: false
  ecr_access_key_id:
    description: "ECR access key ID"
    required: false
  ecr_secret_access_key:
    description: "ECR secret access key"
    required: false
  ecr_region:
    description: "ECR region"
    required: false
    default: "us-east-1"
  ecr_registry:
    description: "ECR registry URL"
    required: false

  custom_image:
    description: "Custom registry image name"
    required: false
  custom_username:
    description: "Custom registry username"
    required: false
  custom_token:
    description: "Custom registry access token"
    required: false
  custom_registry:
    description: "Custom registry URL"
    required: false

outputs:
  dockerhub:
    description: "Whether or not to push to DockerHub"
    value: ${{ steps.customvars.outputs.dockerhub }}
  dockerhub_image:
    description: "DockerHub image name"
    value: ${{ steps.customvars.outputs.dockerhub_image }}

  ghcr:
    description: "Whether or not to push to GitHub Container Registry"
    value: ${{ steps.customvars.outputs.ghcr }}
  ghcr_image:
    description: "GitHub Container Registry image name"
    value: ${{ steps.customvars.outputs.ghcr_image }}

  quay:
    description: "Whether or not to push to Quay"
    value: ${{ steps.customvars.outputs.quay }}
  quay_image:
    description: "Quay image name"
    value: ${{ steps.customvars.outputs.quay_image }}

  harbor:
    description: "Whether or not to push to Harbor"
    value: ${{ steps.customvars.outputs.harbor }}
  harbor_image:
    description: "Harbor image name"
    value: ${{ steps.customvars.outputs.harbor_image }}

  ecr:
    description: "Whether or not to push to ECR"
    value: ${{ steps.customvars.outputs.ecr }}
  ecr_image:
    description: "ECR image name"
    value: ${{ steps.customvars.outputs.ecr_image }}
  ecr_image_url:
    description: "ECR image URL"
    value: ${{ steps.ecr.outputs.imageUrl }}

  custom:
    description: "Whether or not to push to a custom registry"
    value: ${{ steps.customvars.outputs.custom }}
  custom_image:
    description: "Custom registry image name"
    value: ${{ steps.customvars.outputs.custom_image }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # pin@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # pin@v2

    - name: Custom Variables
      id: customvars
      shell: bash
      env:
        inputs_github_ref: ${{ inputs.github_ref }}
        inputs_repository_name: ${{ inputs.repository_name }}
        inputs_platforms: ${{ inputs.platforms }}
        inputs_context: ${{ inputs.context }}
        inputs_dockerfile: ${{ inputs.dockerfile }}
        inputs_force_release: ${{ inputs.force_release }}

        inputs_dockerhub_username: ${{ inputs.dockerhub_username }}
        inputs_dockerhub_token: ${{ inputs.dockerhub_token }}
        inputs_dockerhub_image: ${{ inputs.dockerhub_image }}
        inputs_dockerhub_registry: ${{ inputs.dockerhub_registry }}

        inputs_ghcr_username: ${{ inputs.ghcr_username }}
        inputs_ghcr_token: ${{ inputs.ghcr_token }}
        inputs_ghcr_image: ${{ inputs.ghcr_image }}
        inputs_ghcr_registry: ${{ inputs.ghcr_registry }}

        inputs_quay_username: ${{ inputs.quay_username }}
        inputs_quay_token: ${{ inputs.quay_token }}
        inputs_quay_image: ${{ inputs.quay_image }}
        inputs_quay_registry: ${{ inputs.quay_registry }}

        inputs_harbor_username: ${{ inputs.harbor_username }}
        inputs_harbor_token: ${{ inputs.harbor_token }}
        inputs_harbor_image: ${{ inputs.harbor_image }}
        inputs_harbor_registry: ${{ inputs.harbor_registry }}

        inputs_ecr_access_key_id: ${{ inputs.ecr_access_key_id }}
        inputs_ecr_secret_access_key: ${{ inputs.ecr_secret_access_key }}
        inputs_ecr_region: ${{ inputs.ecr_region }}
        inputs_ecr_image: ${{ inputs.ecr_image }}
        inputs_ecr_registry: ${{ inputs.ecr_registry }}

        inputs_custom_username: ${{ inputs.custom_username }}
        inputs_custom_token: ${{ inputs.custom_token }}
        inputs_custom_image: ${{ inputs.custom_image }}
        inputs_custom_registry: ${{ inputs.custom_registry }}

      run: |
        (
          github_ref="${inputs_github_ref}"
          repository_name="${inputs_repository_name}"

          platforms="${inputs_platforms}"
          context="${inputs_context}"
          dockerfile="${inputs_dockerfile}"

          force_release="${inputs_force_release}"

          dockerhub_username="${inputs_dockerhub_username}"
          dockerhub_token="${inputs_dockerhub_token}"
          dockerhub_image="${inputs_dockerhub_image}"
          dockerhub_registry="${inputs_dockerhub_registry}"

          ghcr_username="${inputs_ghcr_username}"
          ghcr_token="${inputs_ghcr_token}"
          ghcr_image="${inputs_ghcr_image}"
          ghcr_registry="${inputs_ghcr_registry}"

          quay_username="${inputs_quay_username}"
          quay_token="${inputs_quay_token}"
          quay_image="${inputs_quay_image}"
          quay_registry="${inputs_quay_registry}"

          harbor_username="${inputs_harbor_username}"
          harbor_token="${inputs_harbor_token}"
          harbor_image="${inputs_harbor_image}"
          harbor_registry="${inputs_harbor_registry}"

          ecr_access_key_id="${inputs_ecr_access_key_id}"
          ecr_secret_access_key="${inputs_ecr_secret_access_key}"
          ecr_region="${inputs_ecr_region}"
          ecr_image="${inputs_ecr_image}"
          ecr_registry="${inputs_ecr_registry}"

          custom_username="${inputs_custom_username}"
          custom_token="${inputs_custom_token}"
          custom_image="${inputs_custom_image}"
          custom_registry="${inputs_custom_registry}"

          found_credentials="false"
          found_dockerfile="false"
          ok_to_build="false"

          echo -n "is_release="
          if [[ "${github_ref}" =~ refs/tags/v[1-9].* ]] \
          || [[ "${force_release:-false}" =~ [YyTt].* ]] ; then
            echo "true"
          else
            echo "false"
          fi

          echo "platforms=${platforms:-linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6}"
          echo "context=${context:-.}"

          effective_dockerfile="${dockerfile:-${context}/Dockerfile}"
          echo "dockerfile=${effective_dockerfile}"

          if [ -f "${effective_dockerfile}" ] ; then
            found_dockerfile="true"
          fi

          echo -n "dockerhub="
          if [ -n "${dockerhub_username}" ] \
          && [ -n "${dockerhub_token}" ] ; then
            echo "true"
            echo "dockerhub_image=${dockerhub_image:-${dockerhub_username}/${repository_name}}"
            echo "dockerhub_registry=${dockerhub_registry:-docker.io}"
            echo "dockerhub_username=${dockerhub_username}"
            echo "dockerhub_token=${dockerhub_token}"
            found_credentials="true"
          else
            echo "false"
          fi

          echo -n "ghcr="
          if [ -n "${ghcr_username}" ] \
          && [ -n "${ghcr_token}" ] ; then
            echo "true"
            echo "ghcr_image=${ghcr_image:-${ghcr_username}/${repository_name}}"
            echo "ghcr_registry=${ghcr_registry:-ghcr.io}"
            echo "ghcr_username=${ghcr_username}"
            echo "ghcr_token=${ghcr_token}"
            found_credentials="true"
          else
            echo "false"
          fi

          echo -n "quay="
          if [ -n "${quay_username}" ] \
          && [ -n "${quay_token}" ] ; then
            echo "true"
            echo "quay_image=${quay_image:-${quay_username}/${repository_name}}"
            echo "quay_registry=${quay_registry:-quay.io}"
            echo "quay_username=${quay_username}"
            echo "quay_token=${quay_token}"
            found_credentials="true"
          else
            echo "false"
          fi

          echo -n "harbor="
          if [ -n "${harbor_username}" ] \
          && [ -n "${harbor_token}" ] ; then
            echo "true"
            echo "harbor_image=${harbor_image:-${harbor_username}/${repository_name}}"
            echo "harbor_registry=${harbor_registry:-goharbor.io}"
            echo "harbor_username=${harbor_username}"
            echo "harbor_token=${harbor_token}"
            found_credentials="true"
          else
            echo "false"
          fi

          echo -n "ecr="
          if [ -n "${ecr_access_key_id}" ] \
          && [ -n "${ecr_secret_access_key}" ] \
          && [ -n "${ecr_region}" ] ; then
            echo "true"
            echo "ecr_image=${ecr_image:-${repository_name}}"
            echo "ecr_registry=${ecr_registry:-dkr.ecr.${ecr_region}.amazonaws.com}"
            echo "ecr_access_key_id=${ecr_access_key_id}"
            echo "ecr_secret_access_key=${ecr_secret_access_key}"
            echo "ecr_region=${ecr_region}"
            found_credentials="true"
          else
            echo "false"
          fi

          echo -n "custom="
          if [ -n "${custom_username}" ] \
          && [ -n "${custom_token}" ] ; then
            echo "true"
            echo "custom_image=${custom_image:-${custom_username}/${repository_name}}"
            echo "custom_registry=${custom_registry:-localhost:5000}"
            echo "custom_username=${custom_username}"
            echo "custom_token=${custom_token}"
            found_credentials="true"
          else
            echo "false"
          fi

          if [ "$found_credentials" = "true" ] && [ "$found_dockerfile" = "true" ] ; then
            ok_to_build="true"
          fi

          echo "found_credentials=${found_credentials}"
          echo "found_dockerfile=${found_dockerfile}"
          echo "ok_to_build=${ok_to_build}"

        ) >> "$GITHUB_OUTPUT"



      ## Login to DockerHub, GitHub Packages, Quay, Harbor, and Custom registries
    - name: Login to DockerHub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pin@v2
      if: ${{ steps.customvars.outputs.dockerhub == 'true' }}
      with:
        username: "${{ steps.customvars.outputs.dockerhub_username }}"
        password: "${{ steps.customvars.outputs.dockerhub_token }}"
        registry: "${{ steps.customvars.outputs.dockerhub_registry }}"

    - name: Login to GitHub Packages
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pin@v2
      if: ${{ steps.customvars.outputs.ghcr == 'true' }}
      with:
        username: "${{ steps.customvars.outputs.ghcr_username }}"
        password: "${{ steps.customvars.outputs.ghcr_token }}"
        registry: "${{ steps.customvars.outputs.ghcr_registry }}"

    - name: Login to Quay
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pin@v2
      if: ${{ steps.customvars.outputs.quay == 'true' }}
      with:
        username: "${{ steps.customvars.outputs.quay_username }}"
        password: "${{ steps.customvars.outputs.quay_token }}"
        registry: "${{ steps.customvars.outputs.quay_registry }}"

    - name: Login to Harbor
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pin@v2
      if: ${{ steps.customvars.outputs.harbor == 'true' }}
      with:
        username: "${{ steps.customvars.outputs.harbor_username }}"
        password: "${{ steps.customvars.outputs.harbor_token }}"
        registry: "${{ steps.customvars.outputs.harbor_registry }}"

    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@8f09f5bf7451d6b8e3f458240eb4026f9476a18d # pin@v3.0.1
      if: ${{ steps.customvars.outputs.ecr == 'true' }}
      with:
        access-key-id: "${{ steps.customvars.outputs.ecr_access_key_id }}"
        secret-access-key: "${{ steps.customvars.outputs.ecr_secret_access_key }}"
        region: "${{ steps.customvars.outputs.ecr_region }}"

    - name: Fetch ECR account
      id: fetchecr
      run: |
        (
          ecr_account="${{steps.ecr.outputs.account}}"
          ecr_account="${ecr_account:-000000000000}"
          echo "ecr_account=${ecr_account}"
        ) >> "$GITHUB_OUTPUT"

    - name: Login to Custom registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pin@v2
      if: ${{ steps.customvars.outputs.custom == 'true' }}
      with:
        username: "${{ steps.customvars.outputs.custom_username }}"
        password: "${{ steps.customvars.outputs.custom_token }}"
        registry: "${{ steps.customvars.outputs.custom_registry }}"

    # Set image metadata and tags
    - name: Docker metadata
      id: meta
      if: ${{ steps.customvars.outputs.ok_to_build == 'true' }}
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # pin@v5
      with:
        images: |
          name=${{ steps.customvars.outputs.dockerhub_registry }}/${{ steps.customvars.outputs.dockerhub_image }},enable=${{ steps.customvars.outputs.dockerhub == 'true' }}
          name=${{ steps.customvars.outputs.ghcr_registry }}/${{ steps.customvars.outputs.ghcr_image }},enable=${{ steps.customvars.outputs.ghcr == 'true' }}
          name=${{ steps.customvars.outputs.quay_registry }}/${{ steps.customvars.outputs.quay_image }},enable=${{ steps.customvars.outputs.quay == 'true' }}
          name=${{ steps.customvars.outputs.harbor_registry }}/${{ steps.customvars.outputs.harbor_image }},enable=${{ steps.customvars.outputs.harbor == 'true' }}
          name=${{ steps.customvars.outputs.custom_registry }}/${{ steps.customvars.outputs.custom_image }},enable=${{ steps.customvars.outputs.custom == 'true' }}
          name=${{ steps.fetchecr.outputs.ecr_account }}.${{ steps.customvars.outputs.ecr_registry }}/${{ steps.customvars.outputs.ecr_image }},enable=${{ steps.customvars.outputs.ecr == 'true' }}

        tags: |
          type=raw,value=latest,enable=${{ steps.customvars.outputs.is_release == 'true' }}
          type=semver,pattern={{version}},enable=${{ steps.customvars.outputs.is_release == 'true' }}
          type=semver,pattern={{major}},enable=${{ steps.customvars.outputs.is_release == 'true' }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ steps.customvars.outputs.is_release == 'true' }}
          type=edge,branch=main
          type=sha
          type=sha,format=long
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

    # Build and push images
    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # pin@v6.18.0
      if: ${{ steps.customvars.outputs.ok_to_build == 'true' }}
      id: build-push
      with:
        push: true
        sbom: true
        context: ${{ steps.customvars.outputs.context }}
        file: ${{ steps.customvars.outputs.dockerfile }}
        platforms: ${{ steps.customvars.outputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}

    # Update image descriptions (DockerHub, Quay, and Harbor only)
    - name: update DockerHub description
      uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # pin@v1
      if: ${{ steps.customvars.outputs.dockerhub == 'true' && steps.customvars.outputs.ok_to_build == 'true' }}
      with:
        destination_container_repo: ${{ steps.customvars.outputs.dockerhub_image }}
        provider: dockerhub
      env:
        DOCKER_USER: ${{ steps.customvars.outputs.dockerhub_username }}
        DOCKER_PASS: ${{ steps.customvars.outputs.dockerhub_token }}

    - name: update Quay description
      uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # pin@v1
      if: ${{ steps.customvars.outputs.quay == 'true' && steps.customvars.outputs.ok_to_build == 'true' }}
      with:
        destination_container_repo: ${{ steps.customvars.outputs.quay_image }}
        provider: quay
      env:
        DOCKER_APIKEY: ${{ steps.customvars.outputs.quay_token }}

    - name: update Harbor description
      uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # pin@v1
      if: ${{ steps.customvars.outputs.harbor == 'true' && steps.customvars.outputs.ok_to_build == 'true' }}
      with:
        destination_container_repo: ${{ steps.customvars.outputs.harbor_image }}
        provider: harbor2
      env:
        DOCKER_USER: ${{ steps.customvars.outputs.harbor_username }}
        DOCKER_PASS: ${{ steps.customvars.outputs.harbor_token }}
